name: quran_ai
description: "Quran AI"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  #  icons
  cupertino_icons: ^1.0.2

  #  networking
  retrofit: ^4.0.1
  dio: ^5.7.0

  #  state management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.4

  #  navigation
  go_router: ^14.6.2

  # others
  flutter_hooks: ^0.19.0
  get_it: ^7.6.0
  floor: ^1.4.2
  equatable: ^2.0.5
  fluttertoast: ^8.2.2
  awesome_dio_interceptor: ^1.0.0
  flutter_svg: ^2.0.7
  chuck_interceptor: ^2.2.1
  internet_connection_checker: ^1.0.0+1
  loading_indicator: ^3.1.1
  sqflite: ^2.4.1
  keyboard_dismisser: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^8.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lint: ^2.1.2
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/svg/
    - assets/png/
    - assets/quran_images/

  fonts:
    - family: app
      fonts:
        - asset: fonts/icon/app.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900

    - family: Amiri
      fonts:
        - asset: fonts/amiri/Amiri-Regular.ttf
          weight: 400
        - asset: fonts/amiri/Amiri-Bold.ttf
          weight: 700

    - family: Amiri Quran
      fonts:
        - asset: fonts/amiri_quran/AmiriQuran-Regular.ttf
          weight: 400